name: Product Description Generator App CI (Lint, Build)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DATABASE_URL: file:./db.sqlite
      FIRE_API_KEY: "test"
      FIRE_DOMAIN: "test"
      FIRE_PROJECT_ID: "test"
      API_URL: "test"
      AUTH_CALLBACK: "test"
      CLIENT_ID: "test"
      CLIENT_SECRET: "test"
      JWT_KEY: "test"
      LOGIN_URL: "test"
      GOOGLE_API_KEY: "test"
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Lint
        run: npm run build
